config/routes.rb
Rails.application.routes.draw do
  resources :cricketers
  resources :countries
  root 'pages#home'

end

app/models/country.rb
class Country < ActiveRecord::Base

has_many :cricketers
end

app/models/cricketer.rb
class Cricketer < ActiveRecord::Base
    
    belongs_to :country

validates :name, presence: true, length: {minimum: 3, maximum: 80}
validates :fullname, presence: true, length: {minimum: 5, maximum: 800}
validates :score, numericality: {greater_than_or_equal_to: 0}
validates :game, numericality: {greater_than_or_equal_to: 0}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:image, :name, :board, :member, :history)
    end
end

app/controllers/cricketers_controller.rb
class CricketersController < ApplicationController
  before_action :set_cricketer, only: [:show, :edit, :update, :destroy]

  # GET /cricketers
  # GET /cricketers.json
  def index
    @cricketers = Cricketer.all
  end

  # GET /cricketers/1
  # GET /cricketers/1.json
  def show
  end

  # GET /cricketers/new
  def new
    @cricketer = Cricketer.new
  end

  # GET /cricketers/1/edit
  def edit
  end

  # POST /cricketers
  # POST /cricketers.json
  def create
    @cricketer = Cricketer.new(cricketer_params)

    respond_to do |format|
      if @cricketer.save
        format.html { redirect_to @cricketer, notice: 'Cricketer was successfully created.' }
        format.json { render :show, status: :created, location: @cricketer }
        country = Country.find(cricketer_params[:country_id])
@cricketer.build_country(:id => country.id)
        
      else
        format.html { render :new }
        format.json { render json: @cricketer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cricketers/1
  # PATCH/PUT /cricketers/1.json
  def update
    respond_to do |format|
      if @cricketer.update(cricketer_params)
        format.html { redirect_to @cricketer, notice: 'Cricketer was successfully updated.' }
        format.json { render :show, status: :ok, location: @cricketer }
      else
        format.html { render :edit }
        format.json { render json: @cricketer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cricketers/1
  # DELETE /cricketers/1.json
  def destroy
    @cricketer.destroy
    respond_to do |format|
      format.html { redirect_to cricketers_url, notice: 'Cricketer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cricketer
      @cricketer = Cricketer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cricketer_params
      params.require(:cricketer).permit(:name, :fullname, :game, :score, :strength, :country_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
def home
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/cricketers_helper.rb
module CricketersHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/countries/_form.html.erb
<%= form_for(@country) do |f| %>
  <% if @country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
      <% @country.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :board %><br>
    <%= f.text_field :board %>
  </div>
  <div class="field">
    <%= f.label :member %><br>
    <%= f.check_box :member %>
  </div>
  <div class="field">
    <%= f.label :history %><br>
    <%= f.text_area :history %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing Country</h1>

<%= render 'form' %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.erb
<p id="notice"><%= notice %></p>

<h1> CRICKETING COUNTRIES   </h1>

<div class="row">

		<% @countries.each do |country| %>

				<a href="/countries/<%= country.id %>">
					<%= image_tag country.image, class: "country" %>
				</a>


    <% end %>
	</div>	
			

<%= link_to 'New Country', new_country_path %>

app/views/countries/new.html.erb
<h1>New Country</h1>

<%= render 'form' %>

<%= link_to 'Back', countries_path %>

app/views/countries/show.html.erb
<%= image_tag @country.image %>


<p id="notice"><%= notice %></p>


<p>
  <strong>Name:</strong>
  <%= @country.name %>
</p>

<p>
  <strong>Board:</strong>
  <%= @country.board %>
</p>

<p>
  <strong>Member:</strong>
  <%= @country.member %>
</p>

<p>
  <strong>History:</strong>
  <%= @country.history %>
</p>

<%= link_to 'Edit', edit_country_path(@country) %> |
<%= link_to 'Back', countries_path %>

app/views/cricketers/_form.html.erb
<%= form_for(@cricketer) do |f| %>
  <% if @cricketer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cricketer.errors.count, "error") %> prohibited this cricketer from being saved:</h2>

      <ul>
      <% @cricketer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :fullname %><br>
    <%= f.text_field :fullname %>
  </div>
  
  
  <div class="field">
<%= f.label :country_id %><br>
<%= f.select :country_id,
options_for_select(Country.all.collect {|a| ["#{a.name}", a.id]},
selected: (@cricketer.country ? @cricketer.country.id : Country.first.id)),
{} %>
</div>
  
  
  
  <div class="field">
    <%= f.label :game %><br>
    <%= f.number_field :game %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= f.label :strength %><br>
    <%= f.text_field :strength %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cricketers/edit.html.erb
<h1>Editing Cricketer</h1>

<%= render 'form' %>

<%= link_to 'Show', @cricketer %> |
<%= link_to 'Back', cricketers_path %>

app/views/cricketers/index.html.erb
<p id="notice"><%= notice %></p>
<h2>  # Crico Stats #</h2>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Fullname</th>
      <th>Country</th>
      <th>Game</th>
      <th>Score</th>
      <th>Strength</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cricketers.each do |cricketer| %>
      <tr>
        <td><%= cricketer.name %></td>
        <td><%= cricketer.fullname %></td>
        <td><%= (cricketer.country.try(:name) || "NA") %></td>
        <td><%= cricketer.game %></td>
        <td><%= cricketer.score %></td>
        
				<td><%= image_tag cricketer.strength, class: "cricketer" %></td>
        
        <td><%= link_to 'Show', cricketer %></td>
        <td><%= link_to 'Edit', edit_cricketer_path(cricketer) %></td>
        <td><%= link_to 'Destroy', cricketer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<span class="btn">
  <%= link_to 'New Cricketer', new_cricketer_path %>
</span>

app/views/cricketers/new.html.erb
<h1>New Cricketer</h1>

<%= render 'form' %>

<%= link_to 'Back', cricketers_path %>

app/views/cricketers/show.html.erb
<%= image_tag @cricketer.strength %>


<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cricketer.name %>
</p>

<p>
  <strong>Fullname:</strong>
  <%= @cricketer.fullname %>
</p>

<p>
<strong>Country:</strong>
<%= (@cricketer.country.try(:name) || "NA")%>
</p>

<p>
  <strong>Game:</strong>
  <%= @cricketer.game %>
</p>

<p>
  <strong>Score:</strong>
  <%= @cricketer.score %>
</p>


<%= link_to 'Edit', edit_cricketer_path(@cricketer) %> |
<%= link_to 'Back', cricketers_path %>

app/views/layouts/_footer.html.erb
<div class="footer">
<p> &copy; Cricket mania Rights reserved</p>
</div>

app/views/layouts/_navigation.html.erb
    <%=image_tag("captains.png", :size => '330x100', :alt => '+') %>
    <%=image_tag("captains.png", :size => '330x100', :alt => '+') %>
    <%=image_tag("captains.png", :size => '330x100', :alt => '+') %>
    <%=image_tag("captains.png", :size => '330x100', :alt => '+') %>

<div class="navbar navbar-default navbar-fixed-top">
<div class="container">
<div class="navbar-header">

    
<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
<span class="sr-only">Toggle Navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="/"> !!!  Home of Cricket  !!! </a>
</div> <!-- end div class="navbar-header" -->
<div class="collapse navbar-collapse">
<ul class="nav navbar-nav">
    
<li class="active"><%= link_to "Cricketers", "cricketers" %></li>       
<li class="active"><%= link_to "Developers", "cricketers.json" %></li>       

<li><%= link_to "Countries", "countries" %></li>

</ul>
</div> <!-- end div class="collapse navbar-collapse" -->
</div> <!-- end div class="container" -->
</div> <!-- end div class="navbar navbar-default navbar-fixed-top" -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ash</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<body>
  
  <body class="<%= controller.controller_name %>">

<%= render 'layouts/navigation' %>
<div class="container">
<%= yield %>
</div>
<%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/home.html.erb
<h1>
Welcome 

to 

the world of 


CRICKET</h1>

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :fullname %><br>
    <%= f.text_field :fullname %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
        <%= f.text_field :country %>
  </div>
   
<div class="field">
<%= f.label :country_id %><br>
<%= f.select :country_id,
options_for_select(Country.all.collect {|a| ["#{a.name}", a.id]},
selected: (@player.country ? @player.country.id : Country.first.id)),
{} %>
</div>


  
  <div class="field">
    <%= f.label :match %><br>
    <%= f.number_field :match %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= f.label :strength %><br>
    <%= f.select :strength, options_for_select(@strengths.collect {|s| [s[0].humanize, s[0]]},selected: @player.strength), {} %>  
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Players</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Fullname</th>
      <th>Country</th>
      <th>Country</th>
      <th>Match</th>
      <th>Score</th>
      <th>Strength</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.fullname %></td>
        <td><%= player.country %></td>
        
        <td><%= player.match %></td>
        <td><%= player.score %></td>
        <td><%= player.strength %></td>
        
        
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<%= image_tag @cricketer.strength %>


<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Fullname:</strong>
  <%= @player.fullname %>
</p>



<p>
<strong>Nation:</strong>
<%= (@player.nation.try(:name) || "NA")%>
</p>

<p>
  <strong>Match:</strong>
  <%= @player.match %>
</p>

<p>
  <strong>Score:</strong>
  <%= @player.score %>
</p>

<p>
  <strong>Strength:</strong>
  <%= @player.strength %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>